// Syntax Error

// let a = 10;
// console.lo(a);

// try catch finally

// Main Code Comes Under Try Block

// Exception Catch Block

let a = 1;
let b = 2;

try {
  console.log(a + b);

  console.log(c);
} catch (error) {
  console.log("Code Wrong");
} finally {
  console.log("I am going to Exceute");
}
